language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose -f docker-local.yaml run django sh -c "python manage.py test && flake8 --exclude markers/migrations,web/settings.py"