# Generated by Django 3.2.10 on 2021-12-30 22:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessoperator', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('detailurl', models.CharField(max_length=255)),
                ('totaloutstanding', models.IntegerField()),
            ],
            options={
                'db_table': 'current_events',
            },
        ),
    ]
