# Generated by Django 3.2.10 on 2021-12-30 22:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentevents',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
