name: deploy on ec2

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          envs: DJANGO_AWS_ACCESS_KEY_ID,DJANGO_AWS_SECRET_ACCESS_KEY,DJANGO_AWS_STORAGE_BUCKET_NAME
          script: |
            export DJANGO_AWS_ACCESS_KEY_ID=$DJANGO_AWS_ACCESS_KEY_ID
            export DJANGO_AWS_SECRET_ACCESS_KEY=$DJANGO_AWS_SECRET_ACCESS_KEY
            export DJANGO_AWS_STORAGE_BUCKET_NAME=$DJANGO_AWS_STORAGE_BUCKET_NAME
            ./deploy.sh
