name: deploy on ec2

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        env:
          DJANGO_AWS_ACCESS_KEY_ID: ${{ secrets.DJANGO_AWS_ACCESS_KEY_ID }}
          DJANGO_AWS_SECRET_ACCESS_KEY: ${{ secrets.DJANGO_AWS_SECRET_ACCESS_KEY }}
          DJANGO_AWS_STORAGE_BUCKET_NAME: ${{ secrets.DJANGO_AWS_STORAGE_BUCKET_NAME }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          envs: DJANGO_AWS_ACCESS_KEY_ID,DJANGO_AWS_SECRET_ACCESS_KEY,DJANGO_AWS_STORAGE_BUCKET_NAME
          script_stop: true
          script: |
            cd app 
            git pull
            docker-compose -f docker-production.yaml up -d --remove-orphans --build 
            docker-compose -f docker-production.yaml logs | grep django
