name: Django Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the Django Image
        run: docker-compose -f docker-production.yaml build
      - name: Run Django tests
        run: docker-compose -f docker-production.yaml run django sh -c "python manage.py test && flake8 --exclude markers/migrations,web/settings.py"